refatoração na adição de navios
AugustoRickes/es2 pull request #2
Opened 2024-06-21 22:11 UTC by ThaliaXavier

**CÓDIGO NOVO**
![codigo novo](https://github.com/AugustoRickes/es2/assets/163475127/c816453c-2375-4fc6-a621-b80b349ecd4f)

**CÓDIGO ANTIGO**
![codigo antigo](https://github.com/AugustoRickes/es2/assets/163475127/a713b7da-63a4-462b-b2b4-3b377f517801)

2024-06-23 18:00 UTC, AugustoRickes requested changes
ao adicionar os navios precisamos que sejam adicionados os navios de 2 e 3 posições

da uma olhada no while da linha 17 e da linha 32
![Screenshot from 2024-06-23 14-59-34](https://github.com/AugustoRickes/es2/assets/103668139/64222516-1b11-4c45-ad38-3616fc32618d)

2024-06-23 18:13 UTC, AugustoRickes commented on batalha-naval.py
> +    for navio in tipos_navios:
Esse `for` adiciona somente os navios 1 por 1.
Precisamos seguir a regra que estava no código antigo
3 navios de 1 posição
1 navio de 2 posições (que ocupe 2 celulas e que seja adicionado randomicamente, tanto na vertical quanto horizontal)
1 navio de 3 posições (que ocupe 3 celulas e que seja adicionado randomicamente, tanto na vertical quanto horizontal

![Screenshot from 2024-06-23 15-13-13](https://github.com/AugustoRickes/es2/assets/103668139/16abd0f3-bdaa-4a63-abd0-1a34e33107e0)

2024-06-24 16:56 UTC, nathpizzolato approved these changes

2024-07-01 22:35 UTC, ThaliaXavier commented on batalha-naval.py
> +    for navio in tipos_navios:
Ajuste realizado

2024-07-01 22:44 UTC, ThaliaXavier commented
**AJUSTADO CÓDIGO**
![novo](https://github.com/AugustoRickes/es2/assets/163475127/57a98f42-3e36-46f2-9625-b770f381593d)

2024-07-03 01:28 UTC, nathaliakoetz approved these changes

2024-07-04 15:57 UTC, AugustoRickes approved these changes

2024-07-04 15:57 UTC, merged