Mensagem de erro ao colocar coordenadas erradas
AugustoRickes/es2 pull request #4
Opened 2024-06-27 12:34 UTC by PedroCastilhos

Antes
![antes](https://github.com/AugustoRickes/es2/assets/79242129/fa0b7a51-a008-4b5b-9a5a-922c8e796f0c)

Depois
![code](https://github.com/AugustoRickes/es2/assets/79242129/63282065-7e62-4989-b4ee-737abe32e14a)

2024-07-01 21:55 UTC, AugustoRickes requested changes
Quando o navio é acertado e voce atira novamente ele diz que voce errou o tiro

![image](https://github.com/AugustoRickes/es2/assets/103668139/eff43dc6-f4d5-4505-8392-253eedc6cefd)

após atacar onde já tinha o navio
![image](https://github.com/AugustoRickes/es2/assets/103668139/0fa109b9-b1f5-4cde-a368-f7854f3c55c8)

2024-07-03 01:27 UTC, nathaliakoetz approved these changes

2024-07-04 03:56 UTC, PedroCastilhos commented
Arrumei fml

## Antes:
![antes](https://github.com/AugustoRickes/es2/assets/79242129/460fc548-e6bd-48d3-b8b4-19638b403a4e)

## Depois
![depois](https://github.com/AugustoRickes/es2/assets/79242129/9c785279-81fb-4ea2-ab1f-6fb9d96c096d)

2024-07-04 13:00 UTC, nathaliakoetz approved these changes

2024-07-04 16:03 UTC, merged